/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PaperRegistry__factory } from "./PaperRegistry__factory";
export { ReviewManager__factory } from "./ReviewManager__factory";
export { RewardPool__factory } from "./RewardPool__factory";
export { VoteContract__factory } from "./VoteContract__factory";
