/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PaperRegistry } from "./PaperRegistry";
export type { ReviewManager } from "./ReviewManager";
export type { RewardPool } from "./RewardPool";
export type { VoteContract } from "./VoteContract";
